#
# Module manifest for module 'AaTurpin.PSSnapshotManager'
#
# Generated by: aaturpin
#
# Generated on: 7/6/2025
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'AaTurpin.PSSnapshotManager.psm1'

# Version number of this module.
ModuleVersion = '1.0.0'

# Supported PSEditions
# CompatiblePSEditions = @()

# ID used to uniquely identify this module
GUID = 'e7f2a5b8-3c9d-4a1e-8f6b-2d4c7e9a1f3b'

# Author of this module
Author = 'aaturpin'

# Company or vendor of this module
CompanyName = 'Unknown'

# Copyright statement for this module
Copyright = '(c) 2025 aaturpin. All rights reserved.'

# Description of the functionality provided by this module
Description = 'PowerShell module for creating, comparing, and managing network share file snapshots with BITS-based file operations. Provides comprehensive snapshot capture with exclusion pattern support, snapshot comparison for change detection, and efficient file staging operations using Background Intelligent Transfer Service (BITS).'

# Minimum version of the Windows PowerShell engine required by this module
PowerShellVersion = '5.1'

# Name of the Windows PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the Windows PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# DotNetFrameworkVersion = ''

# Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# CLRVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
RequiredModules = @(
    @{
        ModuleName = 'AaTurpin.PSLogger'
        ModuleVersion = '1.0.2'
    },
    @{
        ModuleName = 'AaTurpin.PSConfig'
        ModuleVersion = '1.2.0'
    }
)

# Assemblies that must be loaded prior to importing this module
# RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
# FormatsToProcess = @()

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
# NestedModules = @()

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = 'Get-NetworkShareSnapshot', 'Compare-NetworkShareSnapshots', 
                    'Copy-SnapshotChangesToStaging', 'Move-StagingFilesToNetwork'

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = @()

# Variables to export from this module
VariablesToExport = '*'

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = @()

# DSC resources to export from this module
# DscResourcesToExport = @()

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
FileList = @('README.md', 'LICENSE')

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = 'Snapshot', 'FileSystem', 'NetworkShare', 'BITS', 'Backup', 
               'ChangeDetection', 'FileManagement', 'Enterprise', 'Monitoring', 
               'StagingArea', 'FileTransfer', 'Comparison'

        # A URL to the license for this module.
        LicenseUri = 'https://github.com/aturpin0504/AaTurpin.PSSnapshotManager?tab=MIT-1-ov-file'

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/aturpin0504/AaTurpin.PSSnapshotManager'

        # A URL to an icon representing this module.
        # IconUri = ''

        # ReleaseNotes of this module
        ReleaseNotes = 'Initial release with comprehensive network share snapshot capabilities. Features include: file system snapshot capture with pre-compiled exclusion pattern support for optimal performance, snapshot comparison engine for detecting added/modified/deleted files, BITS-based file copying from network shares to staging areas, BITS-based file moving from staging areas back to network shares with collision handling, comprehensive logging and error tracking, batch processing for large file sets, and integration with AaTurpin.PSConfig for configuration management.'

    } # End of PSData hashtable

} # End of PrivateData hashtable

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}